### ISSUE TITLE
Tolerance Adjustment

### ISSUE THREAD

**Issue by karthikkommalapati** [cran/ROI.plugin.lpsolve#1]
Hi,

Is there a parameter I can use to adjust the tolerance? Basically, I am trying using output from one model as a constraint in another and it seems there is marginal accuracy error taking place and I do not know how to adjust it. Grateful, if you could point me where I can adjust this parameter for `ROI.plugin.lpsolve`. Tried to adjust `epsb` but that did not work.

Kind Regards,
Karthik

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. THanks!

**Comment by karthikkommalapati** [comment]
Apologies
